# GotToVote Config

country: "Zambia"
election_year: "2016"

registration_end_date: "13th August 2014"

api_key: "AIzaSyAwvkIls5mQybyp2R3g4FGiVetNdeVjUeE"
table_id: "1WwZ5OZEXAeFwxVPVyjT8IytEWqpItLy2whADpieX"

google_analytics: 'UA-36749298-5'

# ------------------------------------------------------------------------------
# Jekyll Config

# Handling Reading
safe: true

# Conversion
highlighter: pygments

# ------------------------------------------------------------------------------
# Fusion Tables Config
ft:
  admin_levels:
    - id_col: "Province Code"
      name_col: "Province Name"
      title: "Province"
    - id_col: "District Code"
      name_col: "District Name"
      title: "District"
    - id_col: "Constituency Code"
      name_col: "Constituency Name"
      title: "Constituency"
